"""add onboarding core models

Revision ID: 465d1a9c16b4
Revises: 88b1b1bc1c46
Create Date: 2026-05-11 16:26:47.482764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465d1a9c16b4'
down_revision: Union[str, Sequence[str], None] = '88b1b1bc1c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
