"""add success criteria to onboarding tasks

Revision ID: 5152a5fbf116
Revises: 465d1a9c16b4
Create Date: 2026-05-11 17:02:23.295382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5152a5fbf116'
down_revision: Union[str, Sequence[str], None] = '465d1a9c16b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_tasks', sa.Column('success_criteria', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_tasks', 'success_criteria')
    # ### end Alembic commands ###
