"""add onboarding events

Revision ID: 60d16ea2fc16
Revises: cf4624ae6f9e
Create Date: 2026-05-12 16:23:04.392537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d16ea2fc16'
down_revision: Union[str, Sequence[str], None] = 'cf4624ae6f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcomer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_events_created_at'), 'onboarding_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_onboarding_events_event_type'), 'onboarding_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_onboarding_events_id'), 'onboarding_events', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_events_newcomer_id'), 'onboarding_events', ['newcomer_id'], unique=False)
    op.create_index(op.f('ix_onboarding_events_topic'), 'onboarding_events', ['topic'], unique=False)
    op.create_index(op.f('ix_onboarding_events_user_id'), 'onboarding_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_events_user_id'), table_name='onboarding_events')
    op.drop_index(op.f('ix_onboarding_events_topic'), table_name='onboarding_events')
    op.drop_index(op.f('ix_onboarding_events_newcomer_id'), table_name='onboarding_events')
    op.drop_index(op.f('ix_onboarding_events_id'), table_name='onboarding_events')
    op.drop_index(op.f('ix_onboarding_events_event_type'), table_name='onboarding_events')
    op.drop_index(op.f('ix_onboarding_events_created_at'), table_name='onboarding_events')
    op.drop_table('onboarding_events')
    # ### end Alembic commands ###
