"""add success criteria to onboarding tasks

Revision ID: 67a4ad0267ae
Revises: 8d1aab9ead15
Create Date: 2026-05-12 13:18:39.995926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a4ad0267ae'
down_revision: Union[str, Sequence[str], None] = '8d1aab9ead15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
