"""add plan adjustment suggestions

Revision ID: 6d41118c1e0e
Revises: e75c48a6f8c0
Create Date: 2026-05-13 11:00:13.135983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d41118c1e0e'
down_revision: Union[str, Sequence[str], None] = 'e75c48a6f8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_adjustment_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcomer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggested_changes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['ai_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_adjustment_suggestions_id'), 'plan_adjustment_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_plan_adjustment_suggestions_newcomer_id'), 'plan_adjustment_suggestions', ['newcomer_id'], unique=False)
    op.create_index(op.f('ix_plan_adjustment_suggestions_plan_id'), 'plan_adjustment_suggestions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_adjustment_suggestions_signal_id'), 'plan_adjustment_suggestions', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_adjustment_suggestions_signal_id'), table_name='plan_adjustment_suggestions')
    op.drop_index(op.f('ix_plan_adjustment_suggestions_plan_id'), table_name='plan_adjustment_suggestions')
    op.drop_index(op.f('ix_plan_adjustment_suggestions_newcomer_id'), table_name='plan_adjustment_suggestions')
    op.drop_index(op.f('ix_plan_adjustment_suggestions_id'), table_name='plan_adjustment_suggestions')
    op.drop_table('plan_adjustment_suggestions')
    # ### end Alembic commands ###
