"""add success criteria to onboarding tasks

Revision ID: 8d1aab9ead15
Revises: 5152a5fbf116
Create Date: 2026-05-11 17:08:30.844145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1aab9ead15'
down_revision: Union[str, Sequence[str], None] = '5152a5fbf116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
