"""add_phases_10_to_24

Revision ID: a0e558e8bb3b
Revises: 6d41118c1e0e
Create Date: 2026-05-13 12:46:26.661173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e558e8bb3b'
down_revision: Union[str, Sequence[str], None] = '6d41118c1e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_onboarding_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gap_type', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('affected_newcomers_count', sa.Integer(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_onboarding_gaps_gap_type'), 'company_onboarding_gaps', ['gap_type'], unique=False)
    op.create_index(op.f('ix_company_onboarding_gaps_id'), 'company_onboarding_gaps', ['id'], unique=False)
    op.create_table('person_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_contacts_id'), 'person_contacts', ['id'], unique=False)
    op.create_table('mentor_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_digests_id'), 'mentor_digests', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_digests_mentor_id'), 'mentor_digests', ['mentor_id'], unique=False)
    op.create_table('newcomer_recommended_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcomer_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newcomer_recommended_contacts_id'), 'newcomer_recommended_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_newcomer_recommended_contacts_newcomer_id'), 'newcomer_recommended_contacts', ['newcomer_id'], unique=False)
    op.create_index(op.f('ix_newcomer_recommended_contacts_person_id'), 'newcomer_recommended_contacts', ['person_id'], unique=False)
    op.create_table('onboarding_reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcomer_id', sa.Integer(), nullable=False),
    sa.Column('what_became_clear', sa.Text(), nullable=True),
    sa.Column('what_was_confusing', sa.Text(), nullable=True),
    sa.Column('most_helpful_document', sa.String(length=255), nullable=True),
    sa.Column('most_helpful_person', sa.String(length=255), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_reflections_id'), 'onboarding_reflections', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_reflections_newcomer_id'), 'onboarding_reflections', ['newcomer_id'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcomer_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('blocked_tasks', sa.Integer(), nullable=False),
    sa.Column('open_signals', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('mentor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_snapshots_id'), 'progress_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_progress_snapshots_newcomer_id'), 'progress_snapshots', ['newcomer_id'], unique=False)
    op.create_table('ai_answer_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('newcomer_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['ai_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_answer_feedbacks_id'), 'ai_answer_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_ai_answer_feedbacks_newcomer_id'), 'ai_answer_feedbacks', ['newcomer_id'], unique=False)
    op.create_index(op.f('ix_ai_answer_feedbacks_question_id'), 'ai_answer_feedbacks', ['question_id'], unique=False)
    op.create_index(op.f('ix_ai_answer_feedbacks_user_id'), 'ai_answer_feedbacks', ['user_id'], unique=False)
    op.create_table('ai_signal_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['ai_signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_signal_feedbacks_id'), 'ai_signal_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_ai_signal_feedbacks_signal_id'), 'ai_signal_feedbacks', ['signal_id'], unique=False)
    op.create_index(op.f('ix_ai_signal_feedbacks_user_id'), 'ai_signal_feedbacks', ['user_id'], unique=False)
    op.create_table('blocked_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcomer_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blocker_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['onboarding_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_reports_id'), 'blocked_reports', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_reports_newcomer_id'), 'blocked_reports', ['newcomer_id'], unique=False)
    op.create_index(op.f('ix_blocked_reports_task_id'), 'blocked_reports', ['task_id'], unique=False)
    op.create_index(op.f('ix_blocked_reports_user_id'), 'blocked_reports', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('role_target', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('scope', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'scope')
    op.drop_column('documents', 'role_target')
    op.drop_column('documents', 'domain')
    op.drop_index(op.f('ix_blocked_reports_user_id'), table_name='blocked_reports')
    op.drop_index(op.f('ix_blocked_reports_task_id'), table_name='blocked_reports')
    op.drop_index(op.f('ix_blocked_reports_newcomer_id'), table_name='blocked_reports')
    op.drop_index(op.f('ix_blocked_reports_id'), table_name='blocked_reports')
    op.drop_table('blocked_reports')
    op.drop_index(op.f('ix_ai_signal_feedbacks_user_id'), table_name='ai_signal_feedbacks')
    op.drop_index(op.f('ix_ai_signal_feedbacks_signal_id'), table_name='ai_signal_feedbacks')
    op.drop_index(op.f('ix_ai_signal_feedbacks_id'), table_name='ai_signal_feedbacks')
    op.drop_table('ai_signal_feedbacks')
    op.drop_index(op.f('ix_ai_answer_feedbacks_user_id'), table_name='ai_answer_feedbacks')
    op.drop_index(op.f('ix_ai_answer_feedbacks_question_id'), table_name='ai_answer_feedbacks')
    op.drop_index(op.f('ix_ai_answer_feedbacks_newcomer_id'), table_name='ai_answer_feedbacks')
    op.drop_index(op.f('ix_ai_answer_feedbacks_id'), table_name='ai_answer_feedbacks')
    op.drop_table('ai_answer_feedbacks')
    op.drop_index(op.f('ix_progress_snapshots_newcomer_id'), table_name='progress_snapshots')
    op.drop_index(op.f('ix_progress_snapshots_id'), table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index(op.f('ix_onboarding_reflections_newcomer_id'), table_name='onboarding_reflections')
    op.drop_index(op.f('ix_onboarding_reflections_id'), table_name='onboarding_reflections')
    op.drop_table('onboarding_reflections')
    op.drop_index(op.f('ix_newcomer_recommended_contacts_person_id'), table_name='newcomer_recommended_contacts')
    op.drop_index(op.f('ix_newcomer_recommended_contacts_newcomer_id'), table_name='newcomer_recommended_contacts')
    op.drop_index(op.f('ix_newcomer_recommended_contacts_id'), table_name='newcomer_recommended_contacts')
    op.drop_table('newcomer_recommended_contacts')
    op.drop_index(op.f('ix_mentor_digests_mentor_id'), table_name='mentor_digests')
    op.drop_index(op.f('ix_mentor_digests_id'), table_name='mentor_digests')
    op.drop_table('mentor_digests')
    op.drop_index(op.f('ix_person_contacts_id'), table_name='person_contacts')
    op.drop_table('person_contacts')
    op.drop_index(op.f('ix_company_onboarding_gaps_id'), table_name='company_onboarding_gaps')
    op.drop_index(op.f('ix_company_onboarding_gaps_gap_type'), table_name='company_onboarding_gaps')
    op.drop_table('company_onboarding_gaps')
    # ### end Alembic commands ###
