"""add ai signals

Revision ID: cf4624ae6f9e
Revises: c9d2624e4cbf
Create Date: 2026-05-12 16:08:29.574933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4624ae6f9e'
down_revision: Union[str, Sequence[str], None] = 'c9d2624e4cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcomer_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['newcomer_id'], ['newcomer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_signals_id'), 'ai_signals', ['id'], unique=False)
    op.create_index(op.f('ix_ai_signals_newcomer_id'), 'ai_signals', ['newcomer_id'], unique=False)
    op.create_index(op.f('ix_ai_signals_signal_type'), 'ai_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_ai_question_sources_id'), 'ai_question_sources', ['id'], unique=False)
    op.create_index(op.f('ix_ai_questions_id'), 'ai_questions', ['id'], unique=False)
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_ai_questions_id'), table_name='ai_questions')
    op.drop_index(op.f('ix_ai_question_sources_id'), table_name='ai_question_sources')
    op.drop_index(op.f('ix_ai_signals_signal_type'), table_name='ai_signals')
    op.drop_index(op.f('ix_ai_signals_newcomer_id'), table_name='ai_signals')
    op.drop_index(op.f('ix_ai_signals_id'), table_name='ai_signals')
    op.drop_table('ai_signals')
    # ### end Alembic commands ###
