"""add scoring fields to ai signals

Revision ID: e75c48a6f8c0
Revises: 60d16ea2fc16
Create Date: 2026-05-12 16:40:24.799492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75c48a6f8c0'
down_revision: Union[str, Sequence[str], None] = '60d16ea2fc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "ai_signals",
        sa.Column("score", sa.Float(), nullable=False, server_default="0"),
    )
    op.add_column(
        "ai_signals",
        sa.Column("occurrence_count", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column(
        "ai_signals",
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_signals', 'last_seen_at')
    op.drop_column('ai_signals', 'occurrence_count')
    op.drop_column('ai_signals', 'score')
    # ### end Alembic commands ###
